### ISSUE TITLE
Analog output

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#12]
Humans are looking for wideband 0-5v analog output. Maybe a simple 0-3v output would do?

**Comment by mck1117** [comment]
Which humans? Why? We want to promote rusEFI, so why not encourage CAN?

**Comment by rusefillc** [comment]
Questionable cheap humans for sure, but being known for a good & cheap WBO could be the long shot way to get people familiar and comfortable with RE.

**Comment by shinobisystems** [comment]
Support the addition of an analogue output line (pref 0-5v) on the connector for correlation to gauges for non-EFI / Other ECU applications.. Lets make it available to Everyone out there to prove the Products Superiority (as well as Flexibility)...
