### ISSUE TITLE
Control heater from ECU

### ISSUE THREAD

**Issue by mck1117** [mck1117/wideband#13]
Allow ECU to enable/disable heater control

**Comment by kjngineering** [comment]
A strategy to do this without ECU commands (e.g. "standalone mode") would also be worthwhile.

Can we measure ESR and estimate EGT - does it have any resolution <565*C?

**Comment by mck1117** [comment]
I can test what the ESR looks like with the heater disconnected.

**Comment by mck1117** [comment]
"standalone mode" tracked in #19
