### ISSUE TITLE
Add hardware for onboard voltage sensing.

### ISSUE THREAD

**Issue by kjngineering** [mck1117/wideband#16]
Currently the controller uses the voltage sensed at the ECU and transmitted via CAN to adjust the heater PID.
Chassis wiring and ground points could mean reasonable differences between the battery voltage at the module and the ECU.

Suggest incorporating an ADC channel and appropriate divider on the module to measure "local" battery voltage for heater compensation.

**Comment by rusefillc** [comment]
Another argument for same would be having 042 design self-contained.

**Comment by rusefillc** [comment]
https://rusefi.com/forum/viewtopic.php?p=47055#p47055

![image](https://user-images.githubusercontent.com/48498823/216713761-73f71a03-4cdc-4f10-88a2-fc16737a455c.png)

**Comment by rusefillc** [comment]
Another option https://github.com/mck1117/wideband/issues/194

**Comment by mck1117** [comment]
hardware done 6831f5a1ae87e985e1e40e1fd2b6fe2107d40a72
