### ISSUE TITLE
master is broken

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#179]
looks like master is not green since Jan 5 after two commits by @mck1117

**Comment by dron0gus** [comment]
https://github.com/dron0gus/wideband/commit/2318bd1e01328d1e752bdb59344bb1f8bbec9a0b

**Comment by mck1117** [comment]
> [dron0gus@2318bd1](https://github.com/dron0gus/wideband/commit/2318bd1e01328d1e752bdb59344bb1f8bbec9a0b)

pr?

**Comment by dron0gus** [comment]
https://github.com/mck1117/wideband/pull/180
