### ISSUE TITLE
kicad5 or kicad 6?

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#191]
Is this repo using kicad 5 or kicad 6 or is the intention to support both?

**Comment by mck1117** [comment]
as of yesterday it's a split because the module is now 6

**Comment by rusefillc** [comment]
should https://github.com/mck1117/wideband/blob/master/hardware/board_module/wideband_controller.pro be removed?

**Comment by mck1117** [comment]
8dee668662ecc28bb1afb52380e18ca647ca92fd
