### ISSUE TITLE
[dual rev0] No reading for 30 seconds after engine restart

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#215]
I am running my engine for a while i.e. my sensor is hot.

I stop engine, I start it right away

expected result: i get reading soon
actual result: on dual rev0 it takes 30 seconds to get reading over CAN after restart https://rusefi.com/online/view.php?log=1185

**Comment by rusefillc** [comment]
@dron0gus @mck1117 is that a common thing or dual thing?

**Comment by mck1117** [comment]
The first start didn't actually get the sensor hot.  The sensor never got in to closed loop the first time (and certainly didn't for very long), and certainly didn't do it for very long. The thermal conductivity out of the sensing element is significant - the element itself is relatively light for fast warmup, which means it cools off quick too.

Everything here looks normal to me.

![image](https://user-images.githubusercontent.com/568254/223067401-bef74f42-ac2f-468b-bd39-19ac7deb3ae8.png)

**Comment by mck1117** [comment]
Is that controller using internal vbatt measurement (which might be bogus?) or listening to vbatt from rusEFI?

**Comment by rusefillc** [comment]
this same sensor was running 29 of the previous 30 minutes, i would assume it to be pretty warm

no idea on vbatt, 2chan next rev is a week away from NJ

**Comment by mi-hol** [comment]
@rusefillc just reading thru the comments and was wondering if "the ball" (= answer last question) is not "laying in your court"?

**Comment by rusefillc** [comment]
closing due concerns about dual-dev0 vbatt implementation
