### ISSUE TITLE
Bosch sensors

### ISSUE THREAD

**Issue by ChubbyBunny1** [mck1117/wideband#246]
Not sure if here is the correct place to ask a question.
I have bought an bosch LSU4.9 that is specific fitment for some vehicles. The part number is 0258017617. Is there any chance that this sensor is specific to some vehicle ECUs? Also what are the differences on theese all bosch LSU4.9 sensors apart from their cable length?

**Comment by ChubbyBunny1** [comment]
Thanks for the info, i bought it from theese generic online parts store where you place your VIN and it gives you parts for your car with differnt pricing and company selections. It says bosch and the price was 60euros. Once arrived, i compared it to known original bosch LSU4.9 and the writings and the markings seemed legit.

**Comment by mck1117** [comment]
I'll close for now then. If you end up having a problem with a particular (but legitimate Bosch) sensor, come back and we'll have a look.
