### ISSUE TITLE
is anything broken on this log?

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#279]
![image](https://github.com/mck1117/wideband/assets/48498823/c4ecd127-78c1-4005-9787-6a40ca5354ac)

[wbo-log.zip](https://github.com/mck1117/wideband/files/13345168/wbo-log.zip)

**Comment by mck1117** [comment]
the state of the heater request should be in that log too

**Comment by mck1117** [comment]
Looks like the ECU isn't requesting the heater to be on, so it isn't trying to heat. Everything looks fine from WBO side.
