### ISSUE TITLE
how fast do we expect things to start?

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#296]
hellen 042
first release

not first start today - exhaust and sensor are not completely cold

yet it seems to take ~45 seconds to see WBO reasing
(also all that time fault code is just 0 maybe I shall migrate to fresh binary)

![image](https://github.com/mck1117/wideband/assets/48498823/6eb7c4b2-ffae-4e49-852f-1934231928b2)
[2023-11-22_14.52.35 with sensor.mlg.zip](https://github.com/mck1117/wideband/files/13443961/2023-11-22_14.52.35.with.sensor.mlg.zip)

![javaw_nnLtcqaWx2](https://github.com/mck1117/wideband/assets/48498823/2bc9dc15-c850-4785-aa6b-4fa6d498bd24)

**Comment by rusefillc** [comment]
Now with today snapshot https://github.com/rusefi/wideband/releases/tag/20231122-2 60 seconds to report AFR.

is it a coincidence that I had to touch throttle to get reading? Can wideband detect "too lean" and "too rich" and report those as separate states?

[2023-11-22_21.56.09 mck master.mlg.zip](https://github.com/mck1117/wideband/files/13445713/2023-11-22_21.56.09.mck.master.mlg.zip)

![image](https://github.com/mck1117/wideband/assets/48498823/cedeac48-81f7-4712-a633-c3388a443c70)

**Comment by mck1117** [comment]
@rusefillc give it another try with current master

**Comment by mck1117** [comment]
> is it a coincidence that I had to touch throttle to get reading?

nope, that's just a coincidence.

> Can wideband detect "too lean" and "too rich" and report those as separate states?

It could detect that the pump drive is pinned against the stop (and so the nernst voltage isn't being controlled at ~0.45v), we could at least clear the valid bit when that happens.

**Comment by rusefillc** [comment]
latest artifact is silent on the CANbus. just reverted to the not-hanging version and CANbus has returned

will now try latest one more time

**Comment by rusefillc** [comment]
progress! we now get AFR in about 20 seconds from engine start

![image](https://github.com/mck1117/wideband/assets/48498823/3506ccf9-447e-4858-bfac-36b06621acad)
[2023-11-22_22.55.22 ver3.mlg.zip](https://github.com/mck1117/wideband/files/13445907/2023-11-22_22.55.22.ver3.mlg.zip)

**Comment by mck1117** [comment]
> clear the valid bit when that happens

this is detected and transmitted in ea46db500f6f59fcefe6273ae104fb3fde2bce23
