### ISSUE TITLE
042 master hangs up after a couple of seconds

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#297]
just programmed https://github.com/mck1117/wideband/commit/f784d5d5b91b0d4528596ff69e7f543b37e84ff9 artifact into hardware which is known to run https://github.com/mck1117/wideband/releases/tag/first-release

I see a second of green and blue LED blinking and then both lights go off. Also no data on the CANbus

**Comment by mck1117** [comment]
it's overflowing RAM and for some reason the linker isn't catching it
