### ISSUE TITLE
DBC file broken

### ISSUE THREAD

**Issue by dynfer** [mck1117/wideband#305]
The DBC file when viewing its source or via a tool displays an bogus frame ID.

![obraz](https://github.com/mck1117/wideband/assets/102673508/4453c50c-6afa-4261-b818-b57f630646c2)
![obraz](https://github.com/mck1117/wideband/assets/102673508/d5456e0b-94b9-43f6-9060-8824b73206db)

Tested on:
https://www.csselectronics.com/pages/dbc-editor-can-bus-database

VSCode extension
![obraz](https://github.com/mck1117/wideband/assets/102673508/526cb818-458a-4e7e-998b-d755c8e11695)

https://github.com/mck1117/wideband/blob/master/wideband-can.dbc

**Comment by rusefillc** [comment]
@dynfer I would assume that vector CANdb++ is _the_ official too? Is not that tool free?

DBC is a proprietary standard by vector is not it?

**Comment by mck1117** [comment]
I created it and it opens just fine in Kvaser Database Editor:

<img width="1026" alt="image" src="https://github.com/mck1117/wideband/assets/568254/c186ff6d-fbe6-4e39-b0a4-b8912592b98a">

**Comment by dynfer** [comment]
@rusefillc to my knowledge its the official however the program is not free to use hence the other tools I've used to view it.
If it is proprietary I cannot tell.

@mck1117 I assume then this adress is correct and not an error?

**Comment by mck1117** [comment]
That address is correct, yes.

**Comment by dynfer** [comment]
All clear thanks
