### ISSUE TITLE
F103 no longer blinks

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#43]
F103 FW was blinking green LED before https://github.com/mck1117/wideband/commit/23a05968d3eaa2c6a9e326138c931f02467fbbad
F103 FW no longer blinks green LED after https://github.com/mck1117/wideband/commit/23a05968d3eaa2c6a9e326138c931f02467fbbad

**Comment by mck1117** [comment]
try again with 660dad473ce2e0721438f7be5749fd3e449680c7

**Comment by rusefillc** [comment]
it's blinking again!

**Comment by mck1117** [comment]
OK, I guess something didn't like 64MHz.  Let's stay at 48 for now then, and maybe speed it up later.
