### ISSUE TITLE
F103 CAN baud rate

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#44]
Steps to reproduce:
no real WBO hardware needed, blue pull and logic analyzer should be enough (?)

```
cd firmware
make -j12 BOARD=f1_dave
```

before https://github.com/mck1117/wideband/commit/86034506b07e8c83ea32b3456d0b44037c6cc9da we had

![image](https://user-images.githubusercontent.com/48498823/149410041-d6c7f5df-77e6-4c5d-a9e5-570184e339d2.png)

![image](https://user-images.githubusercontent.com/48498823/149410095-320df007-3149-4678-92ca-b066628660c9.png)

**Comment by rusefillc** [comment]
after https://github.com/mck1117/wideband/commit/86034506b07e8c83ea32b3456d0b44037c6cc9da we have 
![image](https://user-images.githubusercontent.com/48498823/149410178-1aa59c08-94b4-4fad-93c0-1aec9b1a0794.png)

**Comment by rusefillc** [comment]
@blundar great news HW works with 250K version of FW

![image](https://user-images.githubusercontent.com/48498823/149410410-43067c0a-9035-41c1-ad97-090c3f32bb60.png)

**Comment by mck1117** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/568254/149424936-12444693-b1b4-4bcf-83b2-c3f02d0d9f1f.png">

**Comment by rusefillc** [comment]
I cannot explain it i just report my test results sorry

**Comment by rusefillc** [comment]
Just to confirm - is it OK to test with a blue pill with logic analyzer?

![IMG_20220123_184153](https://user-images.githubusercontent.com/48498823/150702969-9c168b52-add4-4d9d-bcd3-66dc45f5cbe4.jpg)

![image](https://user-images.githubusercontent.com/48498823/150702981-7f760e66-38fc-4c32-995c-5c1be3bc7fe0.png)

**Comment by thirstyone** [comment]
don't you need some other devices on the bus?

**Comment by rusefillc** [comment]
@thirstyone please consider using more words. We are trying to discuss pretty complex issues here and in my opinion short form is not effective. If you are looking to help please consider typing a bit more works to spell things out a bit more explicitly.

@thirstyone stm32 uses TTL levels on RX and TX pins right? Are you saying that without a real transceiver and without loopback I would never see CAN peripheral TTLing anything readable?

**Comment by mck1117** [comment]
> without loopback I would never see CAN peripheral TTLing anything readable?

tie TX and RX together, with a 1k pullup to 3.3v, you don't need a CAN tranciever, but you may need a "bus" enough to fake it.

**Comment by rusefillc** [comment]
@thirstyone thank you - with real bus I got 8MHz F103 to work! (alligator clips are wired to CANHacker with 120R)

![image](https://user-images.githubusercontent.com/48498823/150711515-d73f2ad6-2af3-40b4-90b7-b87e384925f4.png)

![IMG_20220123_211117](https://user-images.githubusercontent.com/48498823/150711522-02effd9a-96db-49ac-8295-515368629af4.jpg)

**Comment by rusefillc** [comment]
and F103 WBO firmware CAN works as well as is on this blue pill setup, I have no idea what was wrong with my previous experiments on real WBO board

![image](https://user-images.githubusercontent.com/48498823/150711769-3ab0b8f3-0ea7-47f7-839f-9bfc33504a7f.png)
