### ISSUE TITLE
virtual zero range should be 5v not 3.4v

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#67]
for better AFR range we shall have wider virtual ground range

**Comment by mck1117** [comment]
No need. The circuit was designed to use the full range of the sensor, which we do.

If someone can quantify an actual problem, I am happy to consider it.

**Comment by rusefillc** [comment]
is it about higher current in order to get quicker response time?

**Comment by mck1117** [comment]
> logging used current

We measure that directly with the pump measurement resistor and amp - then convert to lambda.

We do also directly output the raw pump dac value: https://github.com/mck1117/wideband/blob/2167016c169925023510ef98a7c5abf38c2408f5/firmware/can.cpp#L158
