### ISSUE TITLE
DAC and PID nerst control is not the best control strategy

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#68]
usecase: in-range measurment adter out-of-range condition

DAC and PID are not best for return to into range phase of control

suggested soltion: analog control, differential op-amp in diff schematic

**Comment by rusefillc** [comment]
@mck1117 says

our digital loop runs at ~2khz
if it ran at 10hz maybe

but we're much faster than the bandwidth of the sensor

shannon/nyquist say digital and analog are "the same" if you're sufficiently faster than the bandwidth of any signal you care about

**Comment by mck1117** [comment]
I have yet to see a problem with it. I've seen full scale swings (in closed loop!) in <0.1 second.
