### ISSUE TITLE
780C is very imporant

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#69]
nerst cell resistance control by variable voltage - sin wave etc

NIck RMS says that keeping (heater?) at precisely 780C is really important. Sin wave was a suggested implementation detail.

**Comment by mck1117** [comment]
wat?

**Comment by rusefillc** [comment]
@dron0gus do you want to get in touch with Nick RMS and do the translation? :)

**Comment by dron0gus** [comment]
@rusefillc yes, I can try.
