### ISSUE TITLE
4.2 support

### ISSUE THREAD

**Issue by rusefillc** [mck1117/wideband#7]
Would we need just SW or both SW and HW to support 4.2?

**Comment by rusefillc** [comment]
@mck1117 poke? :)

**Comment by rusefillc** [comment]
wow Martin prefers 4.2

Simon confirms that 4.2 does have a thicker ceramic, bosch thinned it on the 4.9 for faster response

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/162306757-4bf896e1-36c1-4a1e-8eb6-30648d9072f4.png)

additional resistor for each LSU type.

22k (existing) = LSU 4.9
6.8k = LSU 4.2
47k = LSU ADV

**Comment by rusefillc** [comment]
@dron0gus need your help. let's plan happy 4.2 in July please :)

![image](https://user-images.githubusercontent.com/48498823/175756404-a7d2f1fc-3107-458c-ac4b-3f40553da0d3.png)
